<script setup>
import { themeColor, contactInfo } from "../config.js";
import Header from "../components/Header.vue"

const lastUpdated = 'August 29, 2025';

function scrollTo(elementId) {
  const element = document.getElementById(elementId);
  if (element) {
    element.scrollIntoView({
      behavior: 'smooth',
      block: 'start'
    });
  }
}
</script>

<template>
  <Header :context="'landing-page'" />
  <div class="terms-container">
    <div class="header-section">
      <h1 class="main-title">Privacy Policy</h1>
      <div class="company-info">
        <p class="last-updated">Last Updated: {{ lastUpdated }}</p>
      </div>
    </div>

    <div class="content-wrapper">
      <nav class="table-of-contents">
        <h3>Table of Contents</h3>
        <ul>
          <li><a href="#interpretation" @click="scrollTo('interpretation')">1. Interpretation & Definitions</a></li>
          <li><a href="#data-collection" @click="scrollTo('data-collection')">2. Collecting and Using Your Personal Data</a></li>
          <li><a href="#retention" @click="scrollTo('retention')">3. Retention of Your Personal Data</a></li>
          <li><a href="#transfer" @click="scrollTo('transfer')">4. Transfer of Your Personal Data</a></li>
          <li><a href="#delete" @click="scrollTo('delete')">5. Deleting Your Personal Data</a></li>
          <li><a href="#disclosure" @click="scrollTo('disclosure')">6. Disclosure of Your Personal Data</a></li>
          <li><a href="#security" @click="scrollTo('security')">7. Security of Your Personal Data</a></li>
          <li><a href="#children" @click="scrollTo('children')">8. Children's Privacy</a></li>
          <li><a href="#links" @click="scrollTo('links')">9. Links to Other Websites</a></li>
          <li><a href="#changes" @click="scrollTo('changes')">10. Changes to this Privacy Policy</a></li>
          <li><a href="#contact" @click="scrollTo('contact')">11. Contact Us</a></li>
        </ul>
      </nav>

      <main class="terms-content">
        <section id="interpretation" class="term-section">
          <h2>1. Interpretation & Definitions</h2>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. 
            The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          <div class="definitions-grid">
            <div class="definition-item"><strong>Account:</strong> A unique account created for You to access our Service or parts of our Service.</div>
            <div class="definition-item"><strong>Affiliate:</strong> An entity that controls, is controlled by or is under common control with a party...</div>
            <div class="definition-item"><strong>Application:</strong> Gates, the software program provided by the Company.</div>
            <div class="definition-item"><strong>Company:</strong> Floating Gates srl, Via Vapitello Rasa 28.</div>
            <div class="definition-item"><strong>Country:</strong> Italy</div>
            <div class="definition-item"><strong>Device:</strong> Any device that can access the Service such as a computer, cellphone, or digital tablet.</div>
            <div class="definition-item"><strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.</div>
            <div class="definition-item"><strong>Service:</strong> Refers to the Application.</div>
            <div class="definition-item"><strong>Service Provider:</strong> Any natural or legal person who processes data on behalf of the Company.</div>
            <div class="definition-item"><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</div>
            <div class="definition-item"><strong>You:</strong> The individual or entity accessing or using the Service.</div>
          </div>
        </section>

        <section id="data-collection" class="term-section">
          <h2>2. Collecting and Using Your Personal Data</h2>
          <h3>Personal Data</h3>
          <p>While using Our Service, We may ask You to provide certain personally identifiable information, including:</p>
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h3>Usage Data</h3>
          <p>
            Usage Data is collected automatically when using the Service and may include IP address, browser type, 
            browser version, pages visited, time spent, device identifiers, and diagnostic data.
          </p>

          <h3>Use of Personal Data</h3>
          <p>
            The Company may use Personal Data to provide and maintain our Service, manage your account, perform contracts, 
            contact You, provide news or offers, manage requests, for business transfers, and other purposes such as analysis 
            and improvement of services.
          </p>
        </section>

        <section id="retention" class="term-section">
          <h2>3. Retention of Your Personal Data</h2>
          <p>Your data is retained only as long as necessary to fulfill the purposes of this Privacy Policy or comply with legal obligations.</p>
        </section>

        <section id="transfer" class="term-section">
          <h2>4. Transfer of Your Personal Data</h2>
          <p>Your information may be processed and stored in locations outside of your country where data protection laws may differ.</p>
        </section>

        <section id="delete" class="term-section">
          <h2>5. Deleting Your Personal Data</h2>
          <p>You have the right to delete or request deletion of your Personal Data. Account settings or direct contact with the Company can facilitate this.</p>
        </section>

        <section id="disclosure" class="term-section">
          <h2>6. Disclosure of Your Personal Data</h2>
          <ul>
            <li>Business Transactions: Transfers in mergers or acquisitions</li>
            <li>Law enforcement: If required by law or government authority</li>
            <li>Other legal requirements: Protect rights, safety, and prevent wrongdoing</li>
          </ul>
        </section>

        <section id="security" class="term-section">
          <h2>7. Security of Your Personal Data</h2>
          <p>We implement industry-standard security measures, but cannot guarantee absolute security of data.</p>
        </section>

        <section id="children" class="term-section">
          <h2>8. Children's Privacy</h2>
          <p>Our Service does not address anyone under 13. We do not knowingly collect information from children under 13.</p>
        </section>

        <section id="links" class="term-section">
          <h2>9. Links to Other Websites</h2>
          <p>Our Service may contain links to external websites. We are not responsible for the privacy practices of third-party sites.</p>
        </section>

        <section id="changes" class="term-section">
          <h2>10. Changes to this Privacy Policy</h2>
          <p>We may update this Privacy Policy from time to time. Updates are effective when posted on this page.</p>
        </section>

        <section id="contact" class="term-section">
          <h2>11. Contact Us</h2>
          <p>For questions about this Privacy Policy, contact us at:</p>
          <div class="contact-info">
            <p>Email: {{ contactInfo.email }}</p>
            <p>Address: {{ contactInfo.address }}</p>
            <p>VAT: {{ contactInfo.vat }}</p>
          </div>
        </section>
      </main>
    </div>
  </div>
</template>

<style scoped>
/* Same styles as your Terms of Service component */
.terms-container {
  max-width: 1800px;
  margin: 0 auto;
  padding: 100px 20px 20px;
  line-height: 1.6;
  color: #333;
}

.header-section {
    text-align: center;
    margin-bottom: 40px;
    padding-bottom: 30px;
    border-bottom: 2px solid #e0e0e0;
}

.main-title {
    font-size: 2.5rem;
    margin: 0 0 20px 0;
    color: v-bind(themeColor);
    font-weight: 700;
}

.last-updated {
    color: #666;
    font-style: italic;
    margin: 0;
}

.content-wrapper {
    display: grid;
    grid-template-columns: 300px 1fr;
    gap: 40px;
    align-items: start;
}

.table-of-contents {
    position: sticky;
    top: 20px;
    background: #f8f9fa;
    padding: 25px;
    border-radius: 8px;
    border: 1px solid #e9ecef;
}

.table-of-contents h3 {
    margin: 0 0 15px 0;
    color: v-bind(themeColor);
    font-size: 1.1rem;
}

.table-of-contents ul {
    list-style: none;
    padding: 0;
    margin: 0;
}

.table-of-contents li {
    margin-bottom: 8px;
}

.table-of-contents a {
    color: #2b6cb0;
    text-decoration: none;
    font-size: 0.9rem;
    cursor: pointer;
    transition: color 0.2s ease;
}

.table-of-contents a:hover {
    color: v-bind(themeColor);
    text-decoration: underline;
}

.terms-content {
    max-width: none;
}

.term-section {
    margin-bottom: 35px;
    scroll-margin-top: 20px;
}

.term-section h2 {
    color: v-bind(themeColor);
    font-size: 1.4rem;
    margin: 0 0 15px 0;
    padding-bottom: 8px;
    border-bottom: 1px solid #e0e0e0;
}

.term-section p {
    margin-bottom: 15px;
    text-align: justify;
}

.term-section ul {
    margin: 15px 0;
    padding-left: 25px;
}

.term-section li {
    margin-bottom: 8px;
}

.definitions-grid {
    display: grid;
    gap: 15px;
    margin: 20px 0;
}

.definition-item {
    background: #f8f9fa;
    padding: 15px;
    border-radius: 6px;
    border-left: 4px solid v-bind(themeColor);
}

.contact-info {
    background: #f8f9fa;
    padding: 20px;
    border-radius: 6px;
    margin: 20px 0;
}

.contact-info p {
    margin: 5px 0;
}

/* Mobile responsiveness same as TOS */
@media (max-width: 1024px) {
    .content-wrapper {
        grid-template-columns: 1fr;
        gap: 30px;
    }
    
    .table-of-contents {
        position: static;
        order: 2;
    }
    
    .terms-content {
        order: 1;
    }
}

@media (max-width: 768px) {
    .terms-container { padding: 15px; }
    .main-title { font-size: 2rem; }
    .table-of-contents { padding: 15px; }
    .term-section h2 { font-size: 1.2rem; }
}

@media (max-width: 480px) {
    .main-title { font-size: 1.8rem; }
    .definitions-grid { gap: 10px; }
    .definition-item { padding: 10px; }
}
</style>
